
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "api-pangbank"
version = "0.1.0"
description = "Source code to PanGBank API"
authors = [
    {name = "JeanMainguy",email = "jean.mainguy@outlook.fr"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi (>=0.115.7,<0.116.0)",
    "sqlmodel (>=0.0.22,<0.0.23)"
]

[project.scripts]
pangbank_db = "app.manage_db.pangbank_db:cli"

[tool.hatch.build.targets.wheel]
packages = ["app"]
