name: CI

on:
  pull_request:
    branches: 
      - '*'
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  API_CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12'] 

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} 
      
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
            python-version: ${{ matrix.python-version }}
            
      - name: Install the project dependencies
        run: |
          uv pip install -e .[dev]
          uv run python -V

      - name: Run flake8 (code style and linting)
        run: |
          # stop the build if there are Python syntax errors or undefined names
          uv run flake8 pangbank_api --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          uv run flake8 pangbank_api --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run the automated tests
        run: uv run pytest --cov=pangbank_api --cov-report=term -vv #--cov-report=xml --cov-report=html

      # TODO: To use when repo is public
      # - name: Generate coverage badge
      #   run: |
      #     pip install genbadge[coverage]
      #     genbadge coverage -i coverage.xml  -o htmlcov/coverage-badge.svg
      #     rm htmlcov/.gitignore
          
      # - name: Publish coverage report to GitHub Pages
      #   if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: htmlcov
      #     branch: gh-pages